apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: devbootcamp.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/enrollments"
        backend:
          service:
            name: enrollments-clusterip-srv
            port: 
              number: 80
      - pathType: Prefix
        path: "/api/p/enrollments"
        backend:
          service:
            name: payments-clusterip-srv
            port: 
              number: 80